# Generated by Django 5.2.2 on 2025-06-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_patrimonio', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('em uso', 'Em uso'), ('manutenção', 'Manutenção'), ('descartado', 'Descartado')], max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
