# Generated by Django 5.2.2 on 2025-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativo',
            old_name='categoria',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='ativo',
            name='hd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ativo',
            name='processador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ativo',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ativo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
